spring:
  application:
    name: API-GATEWAY

    gateway:
      routes:
        - id: customer-service
          uri: lb://CUSTOMER-MGT-SERVICE
          predicates:
            - Path=/customers/**
        
        - id: lead-service
          uri: lb://LEAD-MGT-SERVICE
          predicates:
            - Path=/leads/**
        
        - id: order-service
          uri: lb://ORDER-MGT-SERVICE
          predicates:
            - Path=/orders/**

server:
  port: 9898
