spring:
  application:
    name: API-GATEWAY
  boot:
    admin:
      client:
        url: http://localhost:1111
        enabled: true
        auto-registration: true
        auto-deregistration: true
        instance:
          name: api-gateway
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

server:
  port: 9898
