spring:
  application:
    name: API-GATEWAY

  boot:
    admin:
      client:
        url: http://localhost:1111  # Admin Server URL
        enabled: true
        auto-registration: true
        instance:
          name: api-gateway

  cloud:
    config:
      enabled: false

    gateway:
      routes:
        - id: customer-service
          uri: lb://CUSTOMER-MGT-SERVICE
          predicates:
            - Path=/customers/**
        
        - id: lead-service
          uri: lb://LEAD-MGT-SERVICE
          predicates:
            - Path=/leads/**
        
        - id: order-service
          uri: lb://ORDER-MGT-SERVICE
          predicates:
            - Path=/orders/**

management:
  endpoints:
   web:
    exposure:
      include: "*" # or include: [ "health", "info", "metrics" ]
  endpoint:
   health:
    show-details: always

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

server:
  port: 9898
