spring:
  boot:
    admin:
      client:
        url: http://localhost:1111  # Spring Boot Admin Server URL
        enabled: true
        auto-registration: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:5656/eureka/
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

# You can also define logging level, circuit breaker settings, etc.
#logging:
#  level:
#    root: DEBUG
#    com.batch14: DEBUG
#  pattern:
#    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
