spring:
  application:
    name: CUSTOMER-MGT-SERVICE
  datasource:
    url: jdbc:postgresql://localhost:5432/finalproject_db # Postgres Dabatase URL
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

management:
  endpoints:
   web:
    exposure:
     include: "*" # or include: [ "health", "info", "metrics" ]
  endpoint:
   health:
    show-details: always
server:
  port: 2021
