spring:
  application:
    name: CUSTOMER-MGT-SERVICE
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/finalproject_db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

management:
  endpoints:
   web:
    exposure:
     include: "*" # or include: [ "health", "info", "metrics" ]
  endpoint:
   health:
    show-details: always
server:
  port: 2021
