spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/finalproject_db # Mysql Dabatase URL
    username: root
    password: root

    hikari:
       minimum-idle: 5
       maximum-pool-size: 20
       idle-timeout: 30000
       max-lifetime: 1800000
       connection-timeout: 30000

  jpa:
      database-platform: org.hibernate.dialect.MySQL8Dialect
      hibernate:
        ddl-auto: create
      show-sql: true
      
server:
  port: 8081

