spring:
  application:
    name: LEAD-MGT-SERVICE
  datasource:
    url: jdbc:postgresql://localhost:5432/finalproject_db # Postgres Dabatase URL
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

  boot:
    admin:
      client:
        url: http://localhost:1111
        enabled: true
        auto-registration: true
        auto-deregistration: true
        instance:
          name: lead-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
server:
  port: 3031
