spring:
  application:
    name: LEAD-MGT-SERVICE
  datasource:
    url: jdbc:postgresql://localhost:5432/customer_db # Postgres Dabatase URL
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

server:
  port: 8082
management:
  endpoints:
   web:
    exposure:
     include: "*" # or include: [ "health", "info", "metrics" ]
  endpoint:
   health:
    show-details: always
