spring:
  application:
    name: ORDER-MGT-SERVICE
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/finalproject_db # Mysql Dabatase URL
    username: root
    password: root

  jpa:
      database-platform: org.hibernate.dialect.MySQL8Dialect
      hibernate:
        ddl-auto: create
      show-sql: true
  boot:
     admin:
       client:
         url: http://localhost:1111  # Admin Server URL
         enabled: true
         auto-registration: true
         auto-deregistration: true  # <- This is important!
         instance:
            name: Sales-Service
         

  cloud:
    config:
      enabled: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ # Eureka Server URL
    register-with-eureka: true
    fetch-registry: true

server:
  port: 8083

management:
  endpoints:
   web:
    exposure:
     include: "*" # or include: [ "health", "info", "metrics" ]
  endpoint:
   health:
    show-details: always
#logging:
#  level:
#    root: DEBUG
#    com.batch14: DEBUG
#  pattern:
#    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
