spring:
  application:
    name: SALES-MGT-SERVICE
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/finalproject_db # Mysql Dabatase URL
    username: root
    password: root

  jpa:
      database-platform: org.hibernate.dialect.MySQL8Dialect
      hibernate:
        ddl-auto: create
      show-sql: true

 
